#ifndef DEBUGUIUTILSGLOBAL_H
#define DEBUGUIUTILSGLOBAL_H

#include <QtGlobal>

#if defined(DEBUGUIUTILS_LIBRARY)
 #  define DEBUGUIUTILS_EXPORT Q_DECL_EXPORT
 #else
 #  define DEBUGUIUTILS_EXPORT Q_DECL_IMPORT
 #endif

#endif // DEBUGUIUTILSGLOBAL_H
